# Generated by Django 2.0.1 on 2020-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=80, verbose_name='Name')),
                ('native_name', models.CharField(db_column='NativeName', max_length=80, verbose_name='Native Name')),
                ('alpha2_code', models.CharField(blank=True, db_column='Alpha2Code', max_length=2, null=True, verbose_name='Alpha2 Code')),
                ('alpha3_code', models.CharField(blank=True, db_column='Alpha3Code', max_length=3, null=True, verbose_name='Alpha3 Code')),
                ('numeric_code', models.PositiveSmallIntegerField(blank=True, db_column='NumericCode', null=True, verbose_name='Numeric code')),
                ('flag', models.URLField(blank=True, db_column='Flag', null=True, verbose_name='Flag')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
