# Generated by Django 2.0.1 on 2020-08-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200730_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_24',
            field=models.URLField(blank=True, db_column='Image24', null=True, verbose_name='Image 24'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_512',
            field=models.URLField(blank=True, db_column='Image512', null=True, verbose_name='Image 512'),
        ),
    ]
