# Generated by Django 2.0.1 on 2020-09-06 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200819_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownmember',
            name='image_24',
            field=models.URLField(blank=True, db_column='Image24', help_text='User 24px profile image', verbose_name='Image 24'),
        ),
        migrations.AddField(
            model_name='knownmember',
            name='image_512',
            field=models.URLField(blank=True, db_column='Image512', help_text='User 512px profile image', verbose_name='Image 512'),
        ),
        migrations.AddField(
            model_name='knownmember',
            name='slack_id',
            field=models.CharField(blank=True, db_column='SlackId', max_length=12, verbose_name='Slack ID'),
        ),
        migrations.AddField(
            model_name='knownmember',
            name='tz_offset',
            field=models.IntegerField(blank=True, db_column='TzOffset', default=0, help_text='UTC offset in seconds', validators=[django.core.validators.MinValueValidator(-43200), django.core.validators.MaxValueValidator(54000)], verbose_name='UTC Offset'),
            preserve_default=False,
        ),
    ]
